#!/usr/bin/sh

set -e

cargo build --release
mkdir -p kbuild

nasm -f elf64 src/interrupts/idt.asm -o kbuild/idt.o
ld.lld -T linker.ld -o kbuild/kernel.elf target/x86_64-unknown-none/release/libkernel.a kbuild/idt.o --gc-sections

objcopy --only-keep-debug kbuild/kernel.elf kbuild/kernel.debug
cp kbuild/kernel.debug kbuild/kernel.o
objcopy --strip-debug kbuild/kernel.elf
strip --strip-debug kbuild/kernel.elf